"""Frozen-contract target-free numerical primitives for RC-LTR--ASLO-XF."""

from .core import (
    H1_SLOTS,
    QUADRATURE_ABS_TOL,
    QUADRATURE_POINTS,
    CalDerangement,
    SwitchDecision,
    aumann_shapley,
    aumann_shapley_closure,
    apply_homography,
    base_margin,
    cal_derangement,
    cal_orbit_eligible,
    collapse_exact_components,
    component_evidence,
    decide_one_switch,
    empirical_cal_exceedance,
    fit_homography_dlt,
    four_ledger,
    incremental_margin,
    move_to_front_projection,
    stable_label_ranking,
    stable_label_scores,
    uniform_component_marginal,
)
from .local_runtime import (
    CrossfitSplit,
    HypothesisSet,
    candidate_directional_evidence,
    candidate_directional_features,
    crossfit_split,
    propose_hypotheses,
)
from .verifier import JointDensityRatio, VerifierFit, estimated_log_ratio, fit_training_fold

__all__ = [
    "H1_SLOTS",
    "QUADRATURE_ABS_TOL",
    "QUADRATURE_POINTS",
    "CalDerangement",
    "SwitchDecision",
    "aumann_shapley",
    "aumann_shapley_closure",
    "apply_homography",
    "base_margin",
    "cal_derangement",
    "cal_orbit_eligible",
    "collapse_exact_components",
    "component_evidence",
    "decide_one_switch",
    "empirical_cal_exceedance",
    "fit_homography_dlt",
    "four_ledger",
    "incremental_margin",
    "move_to_front_projection",
    "stable_label_ranking",
    "stable_label_scores",
    "uniform_component_marginal",
    "CrossfitSplit",
    "HypothesisSet",
    "candidate_directional_evidence",
    "candidate_directional_features",
    "crossfit_split",
    "propose_hypotheses",
    "JointDensityRatio",
    "VerifierFit",
    "estimated_log_ratio",
    "fit_training_fold",
]
