#!/usr/bin/env python3
"""Freeze optimization-only fitting of the U4 successor shared bias."""
from __future__ import annotations
import argparse,json
from pathlib import Path
from typing import Any
import freeze_dino_rcde_sr0_mt_p_v2_fit_execution_authority_v96 as H
ROOT=Path(__file__).resolve().parents[1];AUTH="registry/h0/h0_bias_calibrator_optimization_authority_v28_20260824.json";STATUS="H0_BIAS_CALIBRATOR_OPTIMIZATION_EXECUTION_AUTHORIZED"
def req(c:Any,m:str)->None:
    if not c:raise RuntimeError(m)
def read(p:str)->dict[str,Any]:v=json.loads((ROOT/p).read_text());req(isinstance(v,dict),f"JSON drift {p}");return v
def build()->dict[str,Any]:
    u4=read("results/dino_rcde_h0_u4_absolute_gate_v1/result.json");u4v=read("results/dino_rcde_h0_u4_absolute_gate_validation_v1/result.json");raw=read("results/dino_rcde_h0_u4_raw_aggregate_v2/result.json");rawv=read("results/dino_rcde_h0_u4_raw_aggregate_validation_v2/result.json")
    req(u4.get("status")=="H0_U4_CONDITIONAL_ABSOLUTE_VERIFICATION_NO_GO" and u4.get("scientific_GO_or_NO_GO")=="NO_GO" and u4v.get("status")=="H0_U4_ABSOLUTE_GATE_INDEPENDENT_VALIDATION_PASS" and u4v.get("validation_pass") is True,"U4 NO-GO prerequisite drift");req(raw.get("status")=="H0_U4_V2_RAW_SCORE_AGGREGATE_QUARANTINED" and raw.get("matched_count")==567 and raw.get("scientific_metric_count")==0 and rawv.get("status")=="H0_U4_V2_RAW_SCORE_AGGREGATE_INDEPENDENT_VALIDATION_PASS" and rawv.get("validation_pass") is True,"raw optimization source drift")
    b={"contract":H.bind("plan/DINO_RCDE_H0_BIAS_CALIBRATION_SUCCESSOR_CONTRACT_V1_20260824.md"),"literature_report":H.bind("reports/REPORT_H0_U4_NO_GO_LITERATURE_AND_BIAS_REPAIR_DECISION_20260824.md"),"u4_no_go_result":H.bind("results/dino_rcde_h0_u4_absolute_gate_v1/result.json",with_logical=True,immutable=True),"u4_no_go_validation":H.bind("results/dino_rcde_h0_u4_absolute_gate_validation_v1/result.json",with_logical=True,immutable=True),"raw_aggregate":H.bind("results/dino_rcde_h0_u4_raw_aggregate_v2/result.json",with_logical=True,immutable=True),"raw_aggregate_validation":H.bind("results/dino_rcde_h0_u4_raw_aggregate_validation_v2/result.json",with_logical=True,immutable=True),"core":H.bind("src/rc_aslo_xf/dino_rcde_h0_bias_calibrator_v1.py"),"producer":H.bind("programs/fit_dino_rcde_h0_bias_calibrator_v1.py"),"validator":H.bind("programs/validate_dino_rcde_h0_bias_calibrator_v1.py"),"freezer":H.bind("programs/freeze_dino_rcde_h0_bias_calibrator_authority_v28.py"),"launcher":H.bind("slurm/dino_rcde_h0_bias_calibrator_optimization_v1.sbatch"),"test_core":H.bind("tests/test_dino_rcde_h0_bias_calibrator_v1.py"),"test_pipeline":H.bind("tests/test_fit_dino_rcde_h0_bias_calibrator_v1.py"),"test_authority":H.bind("tests/test_freeze_dino_rcde_h0_bias_calibrator_authority_v28.py")}
    v={"schema_version":"rc_h0_bias_calibrator_optimization_authority_v28_20260824","status":STATUS,"track":"H0_BIAS_CALIBRATION_SUCCESSOR","claim_level":"OPTIMIZATION_ONLY_NOT_CONFIRMATION","U4_role":"OPTIMIZATION_ONLY_NOT_CONFIRMATION","calibrator_family":"SHARED_BIAS_ONLY","calibrator_fit_authorized":True,"calibrator_consumption_authorized":False,"model_forward_authorized":False,"model_backward_or_update_authorized":False,"formal_endpoint_scoring_authorized":False,"retrieval_or_ownership_claim_authorized":False,"scientific_GO_or_NO_GO":None,"automatic_stage_advance":False,"next_authorized_stage":None,"fit_contract":{"transform":"READY: z+b; STRUCTURAL_H0: exact 0","parameters":1,"initial_bias":0.0,"dtype":"float64","optimizer":"SAFEGUARDED_NEWTON","max_iterations":64,"gradient_tolerance":1e-12,"regularization":None,"weighting":"EQUAL_RECIPIENT_SUPERGROUP_THEN_QUERY_ROLE_DIRECTION"},"qualification_gates":{"combined_lofo_improvement_vs_init_min":0.01,"heldout_fold_improvement_vs_raw_h_required_count":4,"lofo_bias_span_max":0.15,"margin_max_abs_change_max":1e-12,"structural_h0_exact_zero":True},"output":"results/dino_rcde_h0_bias_calibrator_optimization_v1/result.json","validation_output":"results/dino_rcde_h0_bias_calibrator_optimization_validation_v1/result.json","resource_contract":{"partitions":["dev_cpuonly","cpuonly"],"cpus_per_task":2,"memory_megabytes":8192,"walltime_seconds":600},"bindings":b};v["logical_sha256"]=H.logical(v);return v
def main()->None:
    p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=ROOT/AUTH);a=p.parse_args();req(a.output.resolve(strict=False)==(ROOT/AUTH).resolve(strict=False),"output drift");v=build()
    if a.output.exists():req(json.loads(a.output.read_text())==v,"existing drift")
    else:H.atomic(a.output,v)
    print(json.dumps({"status":STATUS,"logical_sha256":v["logical_sha256"]},sort_keys=True))
if __name__=="__main__":main()
