#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'registry/romav2_colnomic_difficult90_reduction_authority_v1_20260901.json'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def logical(v):return hashlib.sha256(json.dumps({k:x for k,x in v.items() if k!='logical_sha256'},sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest()
def main():
 if OUT.exists():raise RuntimeError('immutable difficult90 authority exists')
 required={'manifest':('results/romav2_colnomic_difficult90_regression_manifest_v1/receipt.json','ROMAV2_COLNOMIC_DIFFICULT90_MANIFEST_BINDING_PASS'),'token_fullrank':('results/romav2_colnomic_difficult90_token_fullrank_prejoin_v1/validation.json','ROMAV2_COLNOMIC_DIFFICULT90_TOKEN_FULLRANK_PREJOIN_VALIDATION_PASS'),'real':('results/romav2_colnomic_difficult90_real_prejoin_v1/validation.json','ROMAV2_COLNOMIC_DIFFICULT90_REAL_PREJOIN_VALIDATION_PASS'),'cbind':('results/romav2_colnomic_difficult90_cbind_prejoin_v1/validation.json','ROMAV2_COLNOMIC_DIFFICULT90_CBIND_PREJOIN_VALIDATION_PASS'),'model_lineage':('results/romav2_colnomic_new_difficult_model_lineage_v1/result.json','ROMAV2_COLNOMIC_NEW_DIFFICULT_MODEL_LINEAGE_FROZEN'),'frozen_gate':('results/romav2_colnomic_frozen_gate_definition_v1/validation.json','ROMAV2_COLNOMIC_FROZEN_GATE_DEFINITION_VALIDATION_PASS')};bindings={}
 for k,(p,status) in required.items():
  x=json.load(open(ROOT/p));assert x['status']==status;bindings[k]={'path':p,'sha256':sha(ROOT/p),'status':status}
 sources=['plan/ROMAV2_COLNOMIC_DIFFICULT90_FROZEN_REGRESSION_V1_20260901.md','programs/reduce_romav2_colnomic_difficult90_regression_v1.py','programs/validate_romav2_colnomic_difficult90_regression_v1.py','programs/reduce_romav2_colnomic_new_difficult_sealed_v1.py','programs/validate_romav2_colnomic_new_difficult_sealed_v1.py','src/rc_aslo_xf/romav2_colnomic_frozen_gate_v1.py'];source_sha={p:sha(ROOT/p) for p in sources};pre=ROOT/'results/romav2_colnomic_difficult90_regression_manifest_v1/prejoin_manifest.json';join=ROOT/'results/romav2_colnomic_difficult90_regression_manifest_v1/target_join_manifest.json';value={'schema_version':'rc_romav2_colnomic_difficult90_reduction_authority_v1_20260901','status':'ROMAV2_COLNOMIC_DIFFICULT90_REDUCTION_AUTHORIZED','claim_level':'OPENED_REGRESSION_REDUCTION_AUTHORITY_NOT_RESULT','bindings':bindings,'source_sha256':source_sha,'manifest':{'prejoin_sha256':sha(pre),'target_join_sha256':sha(join),'query_count':90},'permissions':{'target_join_reader_count':2,'model_forward_authorized':False,'threshold_or_model_change_authorized':False,'all_90_denominator_required':True},'result_path':'results/romav2_colnomic_difficult90_frozen_regression_v1/result.json','validation_path':'results/romav2_colnomic_difficult90_frozen_regression_v1/independent_validation.json','logical_sha256':''};value['logical_sha256']=logical(value);OUT.write_text(json.dumps(value,indent=2,sort_keys=True)+'\n');OUT.chmod(0o444);print(json.dumps({'status':value['status'],'bindings':list(bindings)},sort_keys=True))
if __name__=='__main__':main()
