#!/usr/bin/env python3
import argparse,hashlib,json,sys
from pathlib import Path
import torch
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'src'));sys.path.insert(0,str(ROOT/'programs'))
import materialize_romav2_colnomic_current_runtime_bridge_roma_shard_v1 as bridge
import run_romav2_colnomic_visibility_xf_six_case_v1 as core
from rc_aslo_xf.colnomic_dino_canonical_geometry_v2 import EXIF_ORIENTED_BEFORE_RESIZE,DECODED_RAW_BEFORE_EXIF
from romav2 import RoMaV2
SRC=ROOT/'results/romav2_colnomic_new_difficult_sealed_token_prejoin_v1';AUTH=ROOT/'results/romav2_colnomic_new_difficult_sealed_fullrank_prejoin_v1/validation.json';CONTRACT=ROOT/'plan/ROMAV2_COLNOMIC_NEW_DIFFICULT_C_BIND_CONTROL_V1_20260901.md';OUTROOT=ROOT/'results/romav2_colnomic_new_difficult_sealed_cbind_prejoin_v1';SHIFT=64
def main():
 a=argparse.ArgumentParser();a.add_argument('--shard',type=int,required=True);x=a.parse_args();assert x.shard in range(8);auth=json.load(open(AUTH));assert auth['status']=='ROMAV2_COLNOMIC_NEW_DIFFICULT_SEALED_FULLRANK_PREJOIN_VALIDATION_PASS' and auth['candidate_binding_prejoin_authorized'] is True and auth['sealed_result_reduction_authorized'] is False
 inp=SRC/f'shard{x.shard:02d}/payload.pt';payload=torch.load(inp,map_location='cpu',weights_only=False,mmap=True);out=OUTROOT/f'shard{x.shard:02d}/result.json'
 if out.exists():raise RuntimeError('immutable sealed C_BIND shard exists')
 torch.set_float32_matmul_precision('highest');torch.manual_seed(17);model=RoMaV2();rows=[];ref_sha={}
 for record in payload['records']:
  axis=list(map(int,record['candidate_physical_rows']));assert len(axis)==128 and axis==sorted(axis);qpath=Path(record['query_path']);qimg=core.oriented(qpath);qgeom=bridge.geometry(qpath,record['query_sha256'],f"sealed-cbind-query:{record['query_ordinal']}",record['query_grid_shape'],EXIF_ORIENTED_BEFORE_RESIZE);raw={row:float(v) for row,v in zip(axis,record['candidate_raw_scores'].tolist(),strict=True)};candidates=[]
  for dest,dest_row in enumerate(axis):
   src=(dest+SHIFT)%128;src_row=axis[src];ref=payload['references'][src_row];rpath=Path(ref['source_path']);source_sha=ref_sha.setdefault(src_row,bridge.fsha(rpath));rgeom=bridge.geometry(rpath,source_sha,f'gallery-row:{src_row}',ref['grid_shape'],DECODED_RAW_BEFORE_EXIF);pred=model.match(qimg,core.oriented(rpath));wq=core.cell_means(pred['overlap_AB'][0,...,0].detach().cpu(),qgeom);wr=core.cell_means(pred['overlap_BA'][0,...,0].detach().cpu(),rgeom);real,mass,_=core.score(record['query_tokens'],ref['tokens'],wq,wr);qc,_,_=core.score(record['query_tokens'],ref['tokens'],wq.roll(max(1,wq.numel()//2)),wr);rc,_,_=core.score(record['query_tokens'],ref['tokens'],wq,wr.roll(max(1,wr.numel()//2)));candidates.append({'candidate_position':dest,'physical_row':dest_row,'raw_score':raw[dest_row],'binding_source_position':src,'binding_source_physical_row':src_row,'real_score':float(real),'query_control_score':float(qc),'reference_control_score':float(rc),'visibility_mass':float(mass),'query_map_sha256':hashlib.sha256(wq.contiguous().numpy().tobytes()).hexdigest(),'reference_map_sha256':hashlib.sha256(wr.contiguous().numpy().tobytes()).hexdigest()})
  rows.append({'query_ordinal':record['query_ordinal'],'query_id':record['query_id'],'candidate_count':128,'binding_shift':SHIFT,'binding_fixed_point_count':0,'candidates':candidates,'target_role_read_count':0,'target_insertion_count':0});print(json.dumps({'event':'sealed_cbind_query_ready','shard':x.shard,'ordinal':record['query_ordinal'],'candidate_count':128},sort_keys=True),flush=True)
 value={'schema_version':'rc_romav2_colnomic_new_difficult_sealed_cbind_prejoin_shard_v1_20260901','status':'ROMAV2_COLNOMIC_NEW_DIFFICULT_SEALED_CBIND_PREJOIN_SHARD_READY','claim_level':'SEALED_TARGET_FREE_FIXED_POINT_FREE_CANDIDATE_BINDING_DESTRUCTION','shard':x.shard,'permutation':{'candidate_count':128,'source_position_for_destination':'(destination+64)%128','shift':64,'fixed_point_count':0},'rows':rows,'bindings':{'source_payload_sha256':bridge.fsha(inp),'source_authority_sha256':bridge.fsha(AUTH),'control_contract_sha256':bridge.fsha(CONTRACT)},'target_role_read_count':0,'target_insertion_count':0,'sealed_query_count':len(rows),'sealed_cbind_candidate_score_count':128*len(rows),'model_update_count':0,'logical_sha256':''};value['logical_sha256']=core.logical(value);core.atomic(out,value);print(json.dumps({'status':value['status'],'shard':x.shard,'score_count':value['sealed_cbind_candidate_score_count']},sort_keys=True))
if __name__=='__main__':main()
