#!/usr/bin/env python3
import json,math,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"src"));sys.path.insert(0,str(ROOT/"programs"))
import run_romav2_colnomic_visibility_xf_six_case_v1 as core  # noqa:E402
from rc_aslo_xf.rgh_v9_frozen_colnomic_base_v1 import FrozenColNomicBaseV1  # noqa:E402
SHARDS=ROOT/"results/romav2_colnomic_visibility_xf_full_c128_prejoin_v1";ROLE=ROOT/"results/cw0_rgh_xf_v2_p0_a0_manifest_v2/role_shards";OUT=ROOT/"results/romav2_colnomic_visibility_xf_full_c128_gate_v1/result.json";SELECTION=(394,396,271,285,359,532,368,517,560,341,357,56,519,563,511,345,66,455,356,520,284,399,461,344,364,518,570,459,358,371,72,75)
def ranking(scores,target,rows):
 order=sorted(range(len(scores)),key=lambda i:(-float(scores[i]),int(rows[i])));rival=next(i for i in order if i!=target);return order.index(target)+1,rival,float(scores[target]-scores[rival])
def main():
 if OUT.exists():raise RuntimeError("immutable full-C128 reducer exists")
 docs=[]
 for s in range(4):
  p=SHARDS/f"shard{s:02d}/result.json";x=json.loads(p.read_text());assert x["status"]=="ROMAV2_COLNOMIC_VISIBILITY_XF_FULL_C128_PREJOIN_SHARD_READY" and x["target_role_read_count"]==x["target_insertion_count"]==0 and x["logical_sha256"]==core.logical(x);docs.append(x)
 rows=[r for d in docs for r in d["rows"]];assert tuple(r["execution_ordinal"] for r in rows)==SELECTION;base=FrozenColNomicBaseV1(ROOT);joined=[]
 for r in rows:
  ex=int(r["execution_ordinal"]);role=json.loads((ROLE/f"role_exec{ex:03d}.json").read_text())
  if role.get("target_naturally_present") is not True:joined.append({"execution_ordinal":ex,"query_id":r["query_id"],"target_present":False});continue
  target=int(role["target_candidate_position"]);physical=[x["physical_row"] for x in r["candidates"]];real=[x["real_score"] for x in r["candidates"]];qc=[x["query_control_score"] for x in r["candidates"]];rc=[x["reference_control_score"] for x in r["candidates"]];raw=base.scores(ex,physical).tolist();lr,rv,lm=ranking(real,target,physical);br,_,bm=ranking(raw,target,physical);_,_,qm=ranking(qc,target,physical);_,_,xm=ranking(rc,target,physical);joined.append({"execution_ordinal":ex,"query_id":r["query_id"],"target_present":True,"target_position":target,"local_rank":lr,"base_rank":br,"local_margin":lm,"base_margin":bm,"query_control_margin":qm,"reference_control_margin":xm,"real_gt_query_control":lm>qm,"real_gt_reference_control":lm>xm,"target_rival_maps_distinct":r["candidates"][target]["query_map_sha256"]!=r["candidates"][rv]["query_map_sha256"] and r["candidates"][target]["reference_map_sha256"]!=r["candidates"][rv]["reference_map_sha256"]})
 eligible=[x for x in joined if x["target_present"]];n=len(eligible);local_top=sum(x["local_rank"]==1 for x in eligible);base_top=sum(x["base_rank"]==1 for x in eligible);rescue=sum(x["base_rank"]>1 and x["local_rank"]==1 for x in eligible);brk=sum(x["base_rank"]==1 and x["local_rank"]>1 for x in eligible);qdrop=sum(x["real_gt_query_control"] for x in eligible);rdrop=sum(x["real_gt_reference_control"] for x in eligible);distinct=sum(x["target_rival_maps_distinct"] for x in eligible);mrr=sum(1/x["local_rank"] for x in eligible)/n;base_mrr=sum(1/x["base_rank"] for x in eligible)/n;mean_margin=sum(x["local_margin"] for x in eligible)/n;representation={"eligible":n>=30,"local_top1":local_top>=21,"mean_margin":mean_margin>0,"query_spatial":qdrop>=20,"reference_spatial":rdrop>=20,"candidate_binding":distinct==n};headroom=all(representation.values());direct=headroom and rescue>brk;status="ROMAV2_COLNOMIC_VISIBILITY_XF_FULL_C128_DIRECT_GO" if direct else "ROMAV2_COLNOMIC_VISIBILITY_XF_FULL_C128_HEADROOM_ACTION_REQUIRED" if headroom else "ROMAV2_COLNOMIC_VISIBILITY_XF_FULL_C128_NO_GO";value={"schema_version":"rc_romav2_colnomic_visibility_xf_full_c128_gate_v1_20260831","status":status,"claim_level":"FRESH_INTERNAL_TARGET_FREE_FULL_C128_GATE","contract_sha256":core.sha(ROOT/"plan/ROMAV2_COLNOMIC_VISIBILITY_XF_FULL_C128_GATE_V1_20260831.md"),"prejoin_shard_sha256s":[core.sha(SHARDS/f"shard{s:02d}/result.json") for s in range(4)],"summary":{"selected_query_count":32,"eligible_target_count":n,"target_absent_count":32-n,"local_top1":local_top,"base_top1":base_top,"local_mrr":mrr,"base_mrr":base_mrr,"rescue":rescue,"break":brk,"mean_local_margin":mean_margin,"query_spatial_real_gt_control":qdrop,"reference_spatial_real_gt_control":rdrop,"target_rival_maps_distinct":distinct},"representation_gates":representation,"representation_headroom":headroom,"direct_no_regret":direct,"rows":joined,"target_join_after_all_prejoin_shards":True,"target_insertion_count":0,"opened_read_count":0,"sealed_read_count":0,"P0_authorized":False,"scientific_GO_or_NO_GO":None,"next_authorized_stage":"ROMAV2_COLNOMIC_VISIBILITY_XF_FULL_C128_CONFIRMATION" if direct else "ROMAV2_COLNOMIC_VISIBILITY_XF_HOLD_SWITCH_GATE" if headroom else None,"logical_sha256":""};value["logical_sha256"]=core.logical(value);core.atomic(OUT,value);print(json.dumps({"status":status,"summary":value["summary"],"gates":representation},sort_keys=True))
if __name__=="__main__":main()

