#!/usr/bin/env python3
import hashlib,json,math,os,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];R=ROOT/"results/romav2_colnomic_full_negative_action_gate_v1/result.json";OUT=R.parent/"independent_validation.json";SOURCE=ROOT/"results/cw0_rgh_xf_v2_p0_a0_manifest_v2/source_manifest.json"
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def logical(v):return hashlib.sha256(json.dumps({k:x for k,x in v.items() if k!="logical_sha256"},sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def atomic(p,v):
 fd,n=tempfile.mkstemp(prefix=f".{p.name}.",suffix=".partial",dir=p.parent);q=Path(n)
 try:
  with os.fdopen(fd,"w") as h:json.dump(v,h,indent=2,sort_keys=True);h.write("\n");h.flush();os.fsync(h.fileno())
  q.chmod(0o444);os.link(q,p)
 finally:q.unlink(missing_ok=True)
def main():
 r=json.loads(R.read_text());records={int(x['execution_ordinal']):x for x in json.loads(SOURCE.read_text())['records']};eligible=[x for x in r['actions'] if x['target_present']];base=sum(x['base_correct'] for x in eligible);final=sum(x['final_correct'] for x in eligible);rescue=sum((not x['base_correct']) and x['final_correct'] for x in eligible);brk=sum(x['base_correct'] and (not x['final_correct']) for x in eligible);switch=sum(x['decision']=='SWITCH' for x in eligible);source_ok=all(sha(ROOT/path)==digest for path,digest in (("results/romav2_colnomic_visibility_xf_balanced32_v1/result.json",r['sources']['pair3']),("results/romav2_colnomic_visibility_xf_balanced32_v2/result.json",r['sources']['pair4']),("results/romav2_colnomic_visibility_xf_full_c128_gate_v1/result.json",r['sources']['full_train'])));folds={records[x['execution_ordinal']]['inner_fold'] for x in eligible};weights=r['head']['weight'];summary=r['evaluation_summary'];checks={'envelope':r['logical_sha256']==logical(r) and r['status']=='ROMAV2_COLNOMIC_FULL_NEGATIVE_ACTION_HEADROOM','sources':source_ok and all(sha(ROOT/f"results/romav2_colnomic_visibility_xf_fullnegative_eval_prejoin_v1/shard{s:02d}/result.json")==r['sources']['eval_prejoin'][s] for s in range(4)),'parameter_ledger':r['parameter_count']==7 and len(weights)==6 and all(math.isfinite(float(x)) for x in (*weights,r['head']['bias'])),'fold_isolation':folds=={2} and r['train_query_count']==32 and r['train_pair_count']==64,'action_recompute':summary=={'selected_query_count':len(r['actions']),'eligible_target_count':len(eligible),'target_absent_count':len(r['actions'])-len(eligible),'base_top1':base,'final_top1':final,'rescue':rescue,'break':brk,'switch_count':switch},'decision':r['gates']=={'eligible':len(eligible)>=30,'strict_top1_gain':final>base,'rescue_gt_break':rescue>brk,'break_at_most_one':brk<=1} and all(r['gates'].values()),'boundary':r['romav2_update_count']==r['opened_read_count']==r['sealed_read_count']==0 and r['P0_authorized'] is False and r['scientific_GO_or_NO_GO'] is None};ok=all(checks.values());v={'schema_version':'rc_romav2_colnomic_full_negative_action_gate_validation_v1_20260831','status':'ROMAV2_COLNOMIC_FULL_NEGATIVE_ACTION_INDEPENDENT_VALIDATION_PASS' if ok else 'ROMAV2_COLNOMIC_FULL_NEGATIVE_ACTION_INDEPENDENT_VALIDATION_FAIL','result_sha256':sha(R),'source_decision':r['status'],'checks':checks,'validated_summary':summary,'external_confirmation_authorized':ok,'sealed_data_read_authorized':False,'scientific_GO_or_NO_GO':None,'next_authorized_stage':'FREEZE_EXTERNAL_CONFIRMATION_CONTRACT' if ok else None,'logical_sha256':''};v['logical_sha256']=logical(v);atomic(OUT,v);print(json.dumps({'status':v['status'],'checks':checks,'summary':summary},sort_keys=True));raise SystemExit(0 if ok else 2)
if __name__=='__main__':main()

